# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
plugins_dir:
  - _plugins
plugins:
  - jekyll-auto-image
image: /blog/assets/logo.png
title: 買い物ログ
email: skoji@skoji.jp
description: > # this means to ignore newlines until "baseurl:"
  ねこと酒を愛でるプログラマの日記です。
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://skoji.jp"
timezone: Asia/Tokyo
twitter_username: skoji
github_username: skoji
permalink: /:year/:month/:title.html
defaults:
    -
      scope:
        path: ""
      values:
        type: post
        layout: post
category_slug_map:
    .NET Framework: "net-framework"
    atom: "atom"
    Factor: "factor"
    gepub: "gepub"
    Lisp系: "lisp系"
    LowLevel: "lowlevel"
    Lua: "lua"
    R: "r"
    Ruby: "ruby"
    webapp: "webapp"
    イベント: "イベント"
    このブログについて: "このブログについて"
    その他: "その他"
    ソフトウェア開発: "ソフトウェア開発"
    プログラミング言語: "プログラミング言語"
    休むに似たり: "休むに似たり"
    未分類: "未分類"
    本: "本"
    開発環境: "開発環境"
    電子書籍: "電子書籍"
    Rust: "Rust"
    Mastodon: "Mastodon"
    11日: "11"
    Mac/PC/Palm: macpalm
    blog設定: mt-wp
    お酒: drink
    クルマ・バイク: car-motorcycle
    ソフトウェア: software
    ネタ: ネタ
    休むに似たり: thinkbaka
    写真: photo
    料理: cooking
    日常: day
    映画: movies
    未分類: nocategry
    本: books
    買い物: kaimono
    電書: ebooks
    音楽: music
    目標: resolution
jekyll-archives:
  enabled: [month, categories]
  layouts:
    month: 'month-archive'
    category: 'category-archive'
  permalinks:
    month: '/:year/:month/'
    category: '/category/:name/'
# Build settings
markdown: kramdown
